---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-sidecar
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy-container
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
          args:
            - --provider=oidc
            - --client-id=oauth2-proxy
            - --profile-url=https://auth.dev.krd/connect/userinfo
            - --oidc-issuer-url=https://auth.dev.krd
            - --custom-sign-in-logo=https://gov.krd/media/1099/govkrdlogobig.svg
            - --email-domain=*
            - --http-address=:4180
            - --code-challenge-method=S256
            - --cookie-secure=false
            - --session-cookie-minimal=true

          envFrom:
            - prefix: OAUTH2_PROXY_
              configMapRef:
                name: oauth2-proxy

            - prefix: OAUTH2_PROXY_
              secretRef:
                name: oauth2-proxy

          ports:
            - name: http-proxy
              containerPort: 4180

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 32Mi
